apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-app-config
  namespace: voting-app
  labels:
    app.kubernetes.io/name: voting-app-config
    app.kubernetes.io/part-of: voting-app
data:
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "votes"