apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: voting-app
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: voting-app
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: voting-app
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: voting-app
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: voting-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: voting-app
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP